### ISSUE TITLE
Add section for community widgets

### ISSUE THREAD

**Issue by RisingThumb** [RisingThumb/Travelers-of-Agora-Road-webring#3]
## Hammerkoopa's widget
HTML
```html
<div id='agora-webring'>
    <a class="webring-95-button" href="https://agoraroad.goeshard.org/<member_id>/prev" alt="agora-webring-prev">
        <div id="agora-webring-prev"></div>
    </a>
    <a href="https://risingthumb.github.io/Travelers-of-Agora-Road-webring/" id="agora-webring-title" class="webring-95-button">
        Travelers of Agora Road Webring
    </a>
    <a class="webring-95-button" href="https://agoraroad.goeshard.org/<member_id>/next" alt="agora-webring-next">
        <div id="agora-webring-next"></div>
    </a>
    <div id="webring-background"></div>
</div>
```
CSS
```css
#agora-webring{
  overflow: hidden;
  width: 480px;
  height: 140px;
  display: flex;
  justify-content: space-between;
  border: 5px ridge lightgray;
  align-items: center;
  position: relative;
}

#webring-background{
  width: 480px;
  height: 140px;
  position: absolute;
  z-index: 1;
  background: no-repeat center url("<path_to_image>/agorachan-ident.png");
  background-position-x: 0;
}

#agora-webring #agora-webring-title{
  height: 40px;
  width: 100%;
  z-index: 2;
  align-self: self-start;
  margin-top: 4px;
  text-align: center;
  color: #ffa500;
  text-shadow: -1px 1px 0 #172290, 1px 1px 0 #172290, 1px -1px 0 #172290, -1px -1px 0 #172290;
}

#agora-webring #agora-webring-prev{
  height: 0;
  width: 0;
  border-top: 10px solid transparent;
  border-bottom: 10px solid transparent;
  border-right: 10px solid #172290;
 
}
#agora-webring #agora-webring-next{
  height: 0;
  width: 0;
  border-top: 10px solid transparent;
  border-bottom: 10px solid transparent;
  border-left: 10px solid rgb(23,34,144);
}

.webring-95-button{
  opacity: 0.75;
  z-index: 2;
  display: flex;
  align-items: center;
  justify-content: center;
  height: 50px;
  min-width: 32px;
  border: 3px outset darkgrey;
  background-color: lightgray;
  margin: 16px;
  filter: drop-shadow(2px 4px 6px #000000);
}

.webring-95-button:active{
  border: 3px inset gray;
  background-color: darkgray;
  opacity: 0.5;
}
```
Image

![Image](https://github.com/user-attachments/assets/5754d3ac-4f2b-42a9-b37c-b2886e682b61)

How it looks

![Image](https://github.com/user-attachments/assets/9b0d8dc4-9604-450c-824e-60af7b3d3cd6)

## Some_porcupine's widget

```html
<header class="dark-mode agora-webring" style="font-size: 100%;    font-family: monospace;    min-width: 100%;    margin: 0 auto;    float: left;    height: 4.5em;    display: flex !important;    flex-direction: row !important;    flex-wrap: wrap;    background-image: url(fuji.jpg) !important;    background: round;    align-content: space-around;    justify-content: space-around;    align-items: center;"><a href="https://agoraroad.goeshard.org/someporcupine/prev">◀&nbsp;Back</a><a href="https://risingthumb.github.io/Travelers-of-Agora-Road-webring/">Home</a><a href="https://agoraroad.goeshard.org/someporcupine/rand">/Rnd.</a><a href="https://agoraroad.goeshard.org/someporcupine/next">Next&nbsp;▶</a></header>

/*STYLE - TEXT-COLOR*/
.agora-webring a, .agora-webring a:visited {color: white;}
```
Background image for Porcupine's widget
![Image](https://github.com/user-attachments/assets/5231ea3d-d981-47d9-82b1-c10b3af655c6)
How it looks

![Image](https://github.com/user-attachments/assets/c3507a3f-c22f-4212-a706-e5eba6c75f72)
